### ISSUE TITLE
Contributing Option

### ISSUE THREAD

**Issue by sangeetds** [bjoernmayer/kotlin-react-bootstrap#35]
Hello.
I was hoping to work on a similar project but I landed on your repository and so I thought I would like to contribute to this project if that's ok for you.

**Comment by bjoernmayer** [comment]
Hey,
sorry for the late answer. Work gets so busy when you come back from vacation :D 

That'd be great actually! 
I didn't work on this project for a few weeks. I am still struggling with the nav component. Which is is basically the last component before releasing the first version of this library. 

I'll push what I have. From there on feel free to work on anything you want

**Comment by sangeetds** [comment]
HI!
I get it. I'm getting stuck with too much work these days too.
I'll fork this respository and see what all has been done and will decide what is left. 
Cheers!
